<?php
// Update these three profile URLs once; header icons use them automatically.
$websiteUrl = 'https://plate.kaoutari.cloud';
$linkedinUrl = '';
$githubUrl = '';
$defs=[
'Geometry'=>[
 ['Plate length','plateL',80,'mm'],['Plate width','plateW',70,'mm'],['Plate height','plateH',12,'mm'],['Base thickness','baseT',3,'mm'],['Top thickness','topT',3,'mm'],['Side margin','sideMargin',6,'mm'],['End margin','endMargin',9,'mm'],['Number of passes','numPasses',15,''],['Channel width','channelW',2.5,'mm'],['Channel height','channelH',3,'mm'],['Wall thickness','wallT',1,'mm'],['Vertical shift','yShift',0,'mm'],['Routing mode','routingMode','automatic optimized',['automatic optimized','fixed horizontal']],['Inlet x','inletX',-31,'mm'],['Inlet y','inletY',-25,'mm'],['Outlet x','outletX',31,'mm'],['Outlet y','outletY',25,'mm'],['Port inner diameter','portID',6,'mm'],['Port outer diameter','portOD',10,'mm'],['External port height','portHeight',12,'mm']],
'Thermal'=>[
 ['CPU heat load','heatLoad',180,'W'],['CPU length','cpuL',40,'mm'],['CPU width','cpuW',40,'mm'],['Coverage follows CPU','coverageFollowsCpu',true,'check'],['Cooling zone center x','coverageX',0,'mm'],['Cooling zone center y','coverageY',0,'mm'],['Cooling zone length','coverageL',40,'mm'],['Cooling zone width','coverageW',40,'mm'],['Water inlet temperature','Tin',25,'°C'],['Target water rise','maxRise',8,'K'],['Maximum CPU temperature','maxCpu',75,'°C'],['Ambient temperature','Tamb',25,'°C'],['Ambient pressure','pressure',101325,'Pa'],['Copper emissivity','emissivity',0.10,''],['Top orientation','topOrientation','up',['up','down']],['Include side convection','includeSides',true,'check'],['Include radiation','includeRadiation',false,'check'],['Copper conductivity','copperK',390,'W/mK']],
'Fluid properties'=>[
 ['Water density','waterRho',995,'kg/m³'],['Water viscosity','waterMu',0.00075,'Pa·s'],['Water heat capacity','waterCp',4178,'J/kgK'],['Water conductivity','waterK',0.62,'W/mK'],['Maximum pressure drop','maxDP',35,'kPa'],['Bend loss coefficient','Kbend',1.5,''],['Combined port loss coefficient','Kports',2,'']]
];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cold Plate Thermal Design</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="assets/app.css?v=8" rel="stylesheet"></head>
<body>
<header class="topbar"><div class="brand-wrap"><div class="brand-mark">CP</div><div><h1>Cold Plate Thermal Design</h1><p>Serpentine channel thermal and hydraulic analysis</p></div></div><div class="top-actions"><nav class="social-links" aria-label="External profiles"><a href="<?=htmlspecialchars($websiteUrl)?>" target="_blank" rel="noopener" title="Website" aria-label="Website"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm6.9 6h-3.02a15.9 15.9 0 0 0-1.38-3.2A8.04 8.04 0 0 1 18.9 8ZM12 4c.83 1.2 1.48 2.54 1.88 4h-3.76A13.7 13.7 0 0 1 12 4ZM4.26 14a8 8 0 0 1 0-4h3.4a16.5 16.5 0 0 0 0 4h-3.4Zm.84 2h3.02c.32 1.14.79 2.22 1.38 3.2A8.04 8.04 0 0 1 5.1 16ZM8.12 8H5.1a8.04 8.04 0 0 1 4.4-3.2A15.9 15.9 0 0 0 8.12 8ZM12 20a13.7 13.7 0 0 1-1.88-4h3.76A13.7 13.7 0 0 1 12 20Zm2.28-6H9.72a14.3 14.3 0 0 1 0-4h4.56a14.3 14.3 0 0 1 0 4Zm.22 5.2c.59-.98 1.06-2.06 1.38-3.2h3.02a8.04 8.04 0 0 1-4.4 3.2ZM16.34 14a16.5 16.5 0 0 0 0-4h3.4a8 8 0 0 1 0 4h-3.4Z"/></svg></a><?php if($linkedinUrl!==''):?><a href="<?=htmlspecialchars($linkedinUrl)?>" target="_blank" rel="noopener" title="LinkedIn" aria-label="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 8.2H3.2V21h3.3V8.2ZM4.85 3A1.93 1.93 0 1 0 4.85 6.86 1.93 1.93 0 0 0 4.85 3ZM21 13.66c0-3.85-2.05-5.64-4.79-5.64-2.2 0-3.19 1.21-3.74 2.06V8.2H9.18V21h3.29v-6.34c0-1.67.31-3.29 2.38-3.29 2.04 0 2.06 1.91 2.06 3.4V21H21v-7.34Z"/></svg></a><?php endif?><?php if($githubUrl!==''):?><a href="<?=htmlspecialchars($githubUrl)?>" target="_blank" rel="noopener" title="GitHub" aria-label="GitHub"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 0 0-3.16 19.49c.5.09.68-.22.68-.48v-1.88c-2.78.61-3.37-1.18-3.37-1.18-.45-1.16-1.11-1.47-1.11-1.47-.91-.62.07-.61.07-.61 1 .07 1.53 1.03 1.53 1.03.9 1.53 2.35 1.09 2.92.83.09-.65.35-1.09.64-1.34-2.22-.25-4.56-1.11-4.56-4.94 0-1.09.39-1.98 1.03-2.68-.1-.25-.45-1.27.1-2.64 0 0 .84-.27 2.75 1.02A9.56 9.56 0 0 1 12 6.82c.85 0 1.71.11 2.51.33 1.91-1.29 2.75-1.02 2.75-1.02.55 1.37.2 2.39.1 2.64.64.7 1.03 1.59 1.03 2.68 0 3.84-2.34 4.69-4.57 4.94.36.31.68.92.68 1.86v2.76c0 .27.18.58.69.48A10 10 0 0 0 12 2Z"/></svg></a><?php endif?></nav><span class="demo-chip">DEMO</span></div></header>
<main class="app-shell">
<aside class="control-panel">
 <div class="panel-heading"><div><span class="eyebrow">Design inputs</span><h2>Model configuration</h2></div><button id="reset" class="icon-btn" title="Reset values">↻</button></div>
 <ul class="nav input-tabs" role="tablist"><?php $i=0;foreach($defs as $group=>$fields):$id='input'.++$i;?><li class="nav-item"><button class="nav-link <?=$i===1?'active':''?>" data-bs-toggle="tab" data-bs-target="#<?=$id?>" type="button"><?=htmlspecialchars($group)?></button></li><?php endforeach?></ul>
 <div class="tab-content fields-scroll"><?php $i=0;foreach($defs as $group=>$fields):$id='input'.++$i;?><section class="tab-pane fade <?=$i===1?'show active':''?>" id="<?=$id?>"><div class="field-grid"><?php foreach($fields as $f):
 [$label,$key,$value]=$f; $fourth=$f[3]??''; $fifth=$f[4]??null; $options=is_array($fourth)?$fourth:(is_array($fifth)?$fifth:null); $unit=is_array($fourth)?'':(string)$fourth;
 ?><label class="field-row" for="<?=htmlspecialchars((string)$key)?>"><span class="field-copy"><strong><?=htmlspecialchars((string)$label)?></strong><?php if($unit!==''&&$unit!=='check'):?><small><?=htmlspecialchars($unit)?></small><?php endif?></span><span class="field-control"><?php if($unit==='check'):?><input class="form-check-input cfg" type="checkbox" id="<?=htmlspecialchars((string)$key)?>" <?=$value?'checked':''?>><?php elseif($options!==null):?><select class="form-select cfg" id="<?=htmlspecialchars((string)$key)?>"><?php foreach($options as $o):?><option value="<?=htmlspecialchars((string)$o)?>" <?=$o===$value?'selected':''?>><?=htmlspecialchars((string)$o)?></option><?php endforeach?></select><?php else:?><input class="form-control cfg" type="number" step="any" id="<?=htmlspecialchars((string)$key)?>" value="<?=htmlspecialchars((string)$value)?>"><?php endif?></span></label><?php endforeach?></div></section><?php endforeach?></div>
 <div class="control-footer"><div id="status" class="status-box status-idle"><span class="status-dot"></span><div><strong>Ready</strong><small>Update the geometry or run the complete thermal analysis.</small></div></div><div class="primary-actions"><button class="geometry-btn" id="updateGeometry"><span>Update geometry</span><b>↻</b></button><button class="run-btn" id="calculate"><span>Run calculation</span><b>→</b></button></div><div class="export-grid"><button class="soft-btn" id="excel" disabled>Export Excel</button><button class="soft-btn" id="pdf" disabled>Generate PDF</button></div><button class="ghost-btn" id="representative">Representative PDF</button></div>
</aside>
<section class="workspace">
 <div class="workspace-head"><div><span class="eyebrow">Visualization</span><h2>Engineering dashboard</h2></div><span class="workspace-note">Geometry and calculated fields share the same physical configuration</span></div>
 <div class="workspace-content">
  <section id="geometry"><div class="metric-strip" id="metricStrip"><article><span>Passes</span><strong></strong></article><article><span>Hydraulic length</span><strong></strong></article><article><span>Pressure drop</span><strong></strong></article><article><span>CPU peak</span><strong></strong></article></div><div class="visual-grid"><article class="viz-card"><header><div><span>Figure 01</span><h3>Planar channel route</h3></div><span class="live-pill">2D</span></header><canvas id="geo2d"></canvas></article><article class="viz-card"><header><div><span>Figure 02</span><h3>Plate volume projection</h3></div><span class="live-pill">Interactive 3D</span></header><div class="canvas-stage"><canvas id="geo3d"></canvas><div class="canvas-hint">Drag to rotate · wheel to zoom</div></div></article></div></section>
  <section id="results" class="results-section"><div class="section-heading"><div><span class="eyebrow">Calculated fields</span><h2>Thermal and hydraulic results</h2></div></div><div class="visual-grid"><article class="viz-card"><header><div><span>Figure 03</span><h3>Velocity along hydraulic coordinate</h3></div></header><canvas id="velocity"></canvas></article><article class="viz-card"><header><div><span>Figure 04</span><h3>Coolant temperature along hydraulic coordinate</h3></div></header><canvas id="temperature"></canvas></article><article class="viz-card"><header><div><span>Figure 05</span><h3>Velocity distribution on channel route</h3></div></header><canvas id="velocityMap"></canvas></article><article class="viz-card"><header><div><span>Figure 06</span><h3>Copper temperature distribution</h3></div></header><canvas id="temperatureMap"></canvas></article></div><article class="results-card"><header><div><span>Simulation output</span><h3>Performance summary</h3></div></header><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Quantity</th><th>Value</th><th>Unit</th></tr></thead><tbody id="resultBody"></tbody></table></div></article></section>
 </div>
</section></main>

<div id="calculationOverlay" class="calculation-overlay" aria-hidden="true">
  <div class="calculation-dialog" role="dialog" aria-modal="true" aria-labelledby="calculationTitle">
    <div class="progress-ring" id="progressRing"><span id="progressValue">0%</span></div>
    <div class="progress-copy">
      <strong id="calculationTitle">Evaluating thermal and hydraulic behavior</strong>
      <small id="progressStage">Preparing geometry</small>
      <div class="progress-track"><span id="progressBar"></span></div>
    </div>
  </div>
</div>
<footer>Temporary presentation demo &nbsp; © <?=date('Y')?> Taoufiq KAOUTARI &nbsp; Reduced order estimates for presentation purposes.</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="assets/app.js?v=8"></script></body></html>
